name: nextcloud-linux - Build linux docker image for Nextcloud

on:
  schedule:
    - cron: "15 4 * * 6"   # At 04:15 on Saturday.

defaults:
  run:
    working-directory: nextcloud-linux

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DATE_STAMP: $(date +"%Y%m%d")
      IMAGE_NAME: nextcloud-linux
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker images
      run: |
        docker build . --no-cache --file Dockerfile \
          --tag ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:${{ env.DATE_STAMP }}.${{ github.run_number }} \
          --tag ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:latest

    - name: Docker push images
      run: |
        docker push ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:${{ env.DATE_STAMP }}.${{ github.run_number }}
